apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: {{ template "hermod.fullname" . }}-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "hermod.fullname" . }}-broker-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "hermod.fullname" . }}-broker-broker
    spec:
      containers:
        - name: {{ template "hermod.fullname" . }}-broker-broker
          image: amirgames47/broker:latest
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "500m"
          ports:
            - name: prometheus
              containerPort: 8000
            - name: grpc
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hermod.fullname" . }}-broker-broker-service
  labels:
    app.kubernetes.io/name: {{ template "hermod.fullname" . }}-broker-broker
spec:
  type: NodePort
  ports:
    - name: prometheus
      port: 8000
      nodePort: 31234
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 8080
      nodePort: 31235
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "hermod.fullname" . }}-broker-broker

