version: '3'
services:
  broker:
    image: amirgames47/broker:latest
    platform: linux/amd64
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=broker
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - postgres
      - cassandra

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=concurrent-http-server
    volumes:
      - ../db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - default

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ../db:/var/lib/cassandra

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"

  redis:
    image: redis
    ports:
      - "6379:6379"