global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: broker
    metrics_path:  /metrics
    static_configs:
      - targets: ['192.168.70.193:32342']
  
  - job_name: postgres
    static_configs:
      - targets: ['localhost:9187']

  - job_name: cassandra
    static_configs:
      - targets: ['localhost:9500']

