
echo "\nRunning TestPublishShouldFailOnClosed ..."
go test -run TestPublishShouldFailOnClosed
echo "\nRunning TestSubscribeShouldFailOnClosed ..."
go test -run TestSubscribeShouldFailOnClosed
echo "\nRunning TestFetchShouldFailOnClosed ..."
go test -run TestFetchShouldFailOnClosed
echo "\nRunning TestPublishShouldNotFail ..."
go test -run TestPublishShouldNotFail
echo "\nRunning TestSubscribeShouldNotFail ..."
go test -run TestSubscribeShouldNotFail
echo "\nRunning TestPublishShouldSendMessageToSubscribedChan ..."
go test -run TestPublishShouldSendMessageToSubscribedChan
echo "\nRunning TestPublishShouldSendMessageToSubscribedChans ..."
go test -run TestPublishShouldSendMessageToSubscribedChans
echo "\nRunning TestPublishShouldPreserveOrder ..."
go test -run TestPublishShouldPreserveOrder
echo "\nRunning TestPublishShouldNotSendToOtherSubscriptions ..."
go test -run TestPublishShouldNotSendToOtherSubscriptions
echo "\nRunning TestNonExpiredMessageShouldBeFetchable ..."
go test -run TestNonExpiredMessageShouldBeFetchable
echo "\nRunning TestExpiredMessageShouldNotBeFetchable ..."
go test -run TestExpiredMessageShouldNotBeFetchable
echo "\nRunning TestNewSubscriptionShouldNotGetPreviousMessages ..."
go test -run TestNewSubscriptionShouldNotGetPreviousMessages
echo "\nRunning TestConcurrentSubscribesOnOneSubjectShouldNotFail ..."
go test -run TestConcurrentSubscribesOnOneSubjectShouldNotFail
echo "\nRunning TestConcurrentSubscribesShouldNotFail ..."
go test -run TestConcurrentSubscribesShouldNotFail
echo "\nRunning TestConcurrentPublishOnOneSubjectShouldNotFail ..."
go test -run TestConcurrentPublishOnOneSubjectShouldNotFail
echo "\nRunning TestConcurrentPublishShouldNotFail ..."
go test -run TestConcurrentPublishShouldNotFail
echo "\nRunning TestDataRace ..."
go test -run TestDataRace
go test -bench=. -run=^a
