apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cassandra
    spec:
      containers:
        - image: dockerproxy.bale.ai/cassandra
          name: cassandra
          ports:
            - containerPort: 9042
          resources:
            requests:
              memory: "8Gi"
              cpu: "7"
            limits:
              memory: "9Gi"
              cpu: "8"
      restartPolicy: Always
status: {}
