apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: broker
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: amirgames47/broker:latest
          name: broker
          ports:
            - containerPort: 8080
            - containerPort: 8000
          resources:
            requests:
              memory: "5Gi"
              cpu: "3"
            limits:
              memory: "6Gi"
              cpu: "4"
      restartPolicy: Always
status: {}
